# Generated by Django 5.2.7 on 2025-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("takip_no", models.CharField(max_length=20, unique=True)),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_phone", models.CharField(max_length=20)),
                ("sender_address", models.TextField()),
                ("receiver_name", models.CharField(max_length=100)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("receiver_address", models.TextField()),
                ("durum", models.CharField(default="Hazırlanıyor", max_length=50)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
