# Generated by Django 5.2.7 on 2025-12-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "takip_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Takip Numarası"
                    ),
                ),
                (
                    "gonderen",
                    models.CharField(max_length=100, verbose_name="Gönderen Adı"),
                ),
                ("alici", models.CharField(max_length=100, verbose_name="Alıcı Adı")),
                ("gonderi_tarihi", models.DateField(verbose_name="Gönderi Tarihi")),
                (
                    "tarih_string",
                    models.CharField(
                        default="05 Ara", max_length=20, verbose_name="Görünüm Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kargo",
                "verbose_name_plural": "Kargolar",
            },
        ),
    ]
