# Generated by Django 5.2.7 on 2025-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kargoyonetim", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kargo",
            name="alici_detay",
            field=models.CharField(
                default="Konya / Selçuklu",
                max_length=100,
                verbose_name="Alıcı Şube/Bölge",
            ),
        ),
        migrations.AddField(
            model_name="kargo",
            name="gonderen_detay",
            field=models.CharField(
                default="İstanbul / Şişli",
                max_length=100,
                verbose_name="Gönderen Şube/Bölge",
            ),
        ),
    ]
