# Generated by Django 5.2.7 on 2025-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kargoyonetim", "0002_kargo_alici_detay_kargo_gonderen_detay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kargo",
            name="takip_no",
        ),
        migrations.AddField(
            model_name="kargo",
            name="tracking_number",
            field=models.CharField(
                default="", max_length=50, unique=True, verbose_name="Takip Numarası"
            ),
            preserve_default=False,
        ),
    ]
