# Generated by Django 5.2.7 on 2025-12-19 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kargoyonetim", "0003_remove_kargo_takip_no_kargo_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="kargo",
            name="durum",
            field=models.CharField(
                choices=[
                    ("Hazırlanıyor", "Hazırlanıyor"),
                    ("Yolda", "Yolda"),
                    ("Şubede", "Şubede"),
                    ("Teslim Edildi", "Teslim Edildi"),
                ],
                default="Hazırlanıyor",
                max_length=20,
                verbose_name="Kargo Durumu",
            ),
        ),
        migrations.AddField(
            model_name="kargo",
            name="olusturulma_tarihi",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kargo",
            name="alici_detay",
            field=models.CharField(
                default="Konya / Selçuklu",
                max_length=200,
                verbose_name="Alıcı Şube/Bölge",
            ),
        ),
        migrations.AlterField(
            model_name="kargo",
            name="gonderen_detay",
            field=models.CharField(
                default="İstanbul / Şişli",
                max_length=200,
                verbose_name="Gönderen Şube/Bölge",
            ),
        ),
        migrations.AlterField(
            model_name="kargo",
            name="gonderi_tarihi",
            field=models.DateField(auto_now_add=True, verbose_name="Gönderi Tarihi"),
        ),
        migrations.AlterField(
            model_name="kargo",
            name="tarih_string",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Görünüm Tarihi (Örn: 19 Ara)",
            ),
        ),
    ]
