# Generated by Django 5.2.7 on 2025-12-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kargoyonetim", "0004_kargo_durum_kargo_olusturulma_tarihi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kargo",
            name="alici_telefon",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Alıcı Telefon"
            ),
        ),
        migrations.AddField(
            model_name="kargo",
            name="gonderen_telefon",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Gönderen Telefon"
            ),
        ),
    ]
