# Generated by Django 5.2.7 on 2025-12-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kargoyonetim", "0005_kargo_alici_telefon_kargo_gonderen_telefon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KargoTakipLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eski_durum",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Önceki Durum",
                    ),
                ),
                (
                    "yeni_durum",
                    models.CharField(max_length=50, verbose_name="Yeni Durum"),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True, null=True, verbose_name="İşlem Açıklaması"
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "islem_yapan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlemi Yapan Personel",
                    ),
                ),
                (
                    "kargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hareketler",
                        to="kargoyonetim.kargo",
                        verbose_name="İlgili Kargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kargo Hareketi",
                "verbose_name_plural": "Kargo Hareketleri",
                "ordering": ["-tarih"],
            },
        ),
    ]
