# Generated by Django 5.2.7 on 2025-12-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kargoyonetim", "0006_kargotakiplog"),
    ]

    operations = [
        migrations.AddField(
            model_name="kargo",
            name="alici_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Alıcı E-posta"
            ),
        ),
    ]
