# Generated by Django 5.2.7 on 2025-12-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DestekMesaji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="E-posta Adresi"),
                ),
                ("konu", models.CharField(max_length=200, verbose_name="Konu")),
                ("mesaj", models.TextField(verbose_name="Mesaj")),
                (
                    "tarih",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Mesajı",
                "verbose_name_plural": "Destek Mesajları",
                "ordering": ["-tarih"],
            },
        ),
    ]
